### ISSUE TITLE
Regarding dataset generation

### ISSUE THREAD

**Issue by njan-creative** [PLAN-Lab/CheXRelFormer#1] opened 2023-12-03 08:38 UTC
Can you add the steps for generating the dataset.

**Comment by wangyuanzhuo2001** [comment] 2024-01-03 04:22
I have the same question. I didn't find what the val.csv in code is

**Comment by AmarachiBlessingMbakwe** [comment] 2024-01-11 04:38
We used three datasets – MIMIC-CXR database 2.0.0, MIMIC-CXR-JPG, and Chest Imagenome dataset. These datasets are available in Physionet.
 
1.   Chest Imagenome Dataset Handling: In processing the Chest Imagenome dataset, we used the 'object-object-comparison-relation_evaluation.ipynb' file to generate a comparison relations txt dataset. The object-object-comparison-relation-evaluation script produces a file that includes all the data. We obtained the bounding box from the Bbox coordinates script in the chest imagenome. We ran the 'final_comparison_table.py' (added to the repo) to generate the 'final_comparison_dataset.' Another folder, Splits in the Chest Imagenome dataset, contains train/val/test files. The train/val/test doesn't have most columns as in the file obtained from the object-object-comparison-relation-evaluation script. So, we defined a splitdataset.py (added to the repo), which was used to split the file according to the train/val/test files in the Splits folder. That is splitting the file (obtained from the object-object-comparison-relation-evaluation script) into train/val/test CSV files based on the train/val/test splits in the Splits folder in the Chest Imagenome dataset. We filtered out unique dicom_ids. 
 
2.   MIMIC-CXR Dataset Processing: For the MIMIC-CXR dataset 2.0.0, we used the 'cxr-record-list.csv' file. This file contains paths that we converted from DCM to JPG format. It is combined with the train/val/test split files to extract the required chest x-ray images from the MIMIC-CXR-JPG dataset. You can find the process of extracting the images and the labels in make3folder.py in the CheXRelFormer codebase.
 
Regarding the "val.csv" file mentioned in the code, this file typically contains validation data for the model. It is the val.csv file obtained from running the splitdataset.py.
 
I hope this information sheds some light on the data preprocessing steps in CheXRelFormer. We have also updated the repo by adding two files to the data processing folder. A reading of the chest imagenome dataset paper will be helpful, too.

**Comment by Isminoula** [comment] 2024-01-14 19:49
Please let us know if the issue is fixed, so we can close this ticket. Thank you!

**Comment by wangyuanzhuo2001** [comment] 2024-01-14 19:55
In your instructions, you mentioned in splitdataset.py that the file `bbox_objects_tabular224.txt` can be generated from the Chest Imagnome dataset. However, upon thoroughly examining the dataset, I was unable to locate a script that would produce this specific file. I have searched through all the available scripts for any reference to the creation of `bbox_objects_tabular224.txt`, but my efforts have been unsuccessful. No generated method was found in the Chest Imagnome dataset paper and the work of CheXRelNet neither

**Comment by wangyuanzhuo2001** [comment] 2024-01-14 19:57
Dear researchers of CheXRelFormer，


After receiving your email, I diligently followed the instructions provided and attempted to implement them. However, I encountered a challenge during the process.


In your instructions, you mentioned in splitdataset.py that the file bbox_objects_tabular224.txt can be generated from the Chest Imagnome dataset. However, upon thoroughly examining the dataset, I was unable to locate a script that would produce this specific file. I have searched through all the available scripts for any reference to the creation of bbox_objects_tabular224.txt, but my efforts have been unsuccessful. No generated method was found in the Chest Imagnome dataset paper and the work of CheXRelNet neither


Could you kindly provide some guidance on how to obtain or generate this file? Any additional information or steps that I might have missed would be greatly appreciated. Your expertise in this matter is invaluable to me.


Thank you once again for your time and assistance. I look forward to your guidance on resolving this issue.


Best,
Yuanzhuo Wang






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PLAN-Lab/CheXRelFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 凌晨3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PLAN-Lab/CheXRelFormer] Regarding dataset generation (Issue #1)





 
Please let us know if the issue is fixed, so we can close this ticket. Thank you!

**Comment by AmarachiBlessingMbakwe** [comment] 2024-01-16 19:21
The silver dataset directory contains a "scene_graph.zip" folder with JSON files. In the "utils" directory, there is a "scene_processing.py" script specifically designed to streamline the processing of these JSON files. Additionally, the "analysis" folder includes scripts that facilitate a comprehensive understanding of both the gold and silver datasets.

The file ‘bbox_objects_tabular224.txt’ format for the column headers should be as follows, with tab separation:

image_id    right lung  right apical zone right upper lung zone   right mid lung zone     right lower lung zone   right hilar structures  right costophrenic angle      left lung   left apical zone  left upper lung zone    left mid lung zone      left lower lung zone    left hilar structures   left costophrenic angle mediastinum upper mediastinum cardiac silhouette      trachea

If you encounter further difficulty generating the required files, kindly email us to request the file, providing certification that you can also access ChestImagenome from PhysioNet.

**Comment by yizhipan** [comment] 2024-04-27 09:34
Hello, I am very interested in your research, and I have been trying to generate the dataset based on the content above for a while. However, I encountered difficulties in generating the "bbox_objects_tabular224.txt" file. Could I request this file from you? (My email is 6401210107@hmc.edu.cn, and I have previously sent you an email seeking assistance). I would be extremely grateful if you could provide me with this file. Thank you very much.

**Comment by Isminoula** [comment] 2024-05-04 01:59
Closing as this was resolved offline via email.

**Closed as completed by Isminoula** 2024-05-04 01:59 UTC

**Comment by okdanko0520** [comment] 2025-02-18 09:32
> In your instructions, you mentioned in splitdataset.py that the file `bbox_objects_tabular224.txt` can be generated from the Chest Imagnome dataset. However, upon thoroughly examining the dataset, I was unable to locate a script that would produce this specific file. I have searched through all the available scripts for any reference to the creation of `bbox_objects_tabular224.txt`, but my efforts have been unsuccessful. No generated method was found in the Chest Imagnome dataset paper and the work of CheXRelNet neither


Hello, if you have obtained the missing data files or the steps to process the dataset, could you please share them with me? I can provide proof of access to the dataset.
